203 populate country field in user table when updating users ip address
eclectic-bytech/webcourses-ngx-v4 pull request #210
Opened 2023-03-22 18:57 UTC by SirL3X0N

LocationController.php isn't used in my solution but the tutorials on the service were using are making use of it so I included it in the last commit

2023-03-23 08:26 UTC, bytech-ca requested changes
@SirL3X0N Items that require closer review:

- [ ] Per docs at https://packagist.org/packages/stevebauman/location, changes to app.php are not needed starting Laravel 5.5.
- [ ] Hard coded 89.151.39.138 IP address in LocationController, LoginListener, others?
- [ ] dd dump in LocationController looks out of place
- [ ] Changes to .env.example are needed... LOCATION_TESTING (others?) should be added

Here for any questions you might have.

2023-04-06 08:53 UTC, bytech-ca requested changes

2023-04-06 08:53 UTC, bytech-ca commented on app/Listeners/LoginListener.php
> +        $locationData = \Location::get($userIp);
Let's add a `use` statement instead the fully qualified class name `\Location` (see [this issue](https://github.com/eclectic-bytech/webcourses-ngx-v4/issues/192) for an example in the final comment's linked commit.) Also checkout [this 5 minute tutorial on name spaces](https://symfonycasts.com/screencast/php-namespaces/namespaces) that explains this implementation. 

The [official docs](https://packagist.org/packages/stevebauman/location) recommend putting an if statement around the Location::Get. This won't work inside `$event->user->update`. To get around that, we can set the country code to `XYZ` and then update it with a real one if found. This way there's a value for the update statement, even if the GeoID fails for any reason.

2023-04-06 08:53 UTC, bytech-ca commented on app/Listeners/LoginListener.php
> -        //
An empty function might break tests, other things. Let's re-add the comment slashes.

2023-04-06 08:53 UTC, bytech-ca commented on app/Listeners/LoginListener.php
Route and Request imports might not be needed after making changes listed below.

2023-04-15 17:18 UTC, SirL3X0N commented
@bytech-ca  ready for review

2023-04-20 13:21 UTC, merged